global using System.Windows.Input;
global using Bunit;
global using FluentAssertions;
global using Markdig.Syntax;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.JSInterop;
global using Moq;
global using Xunit;
